project_name: awdb

builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

nfpms:
  - replacements:
      amd64: 64-bit
      386: 32-bit
    vendor: RightMesh
    maintainer: Frazer Seymour <frazer@rightmesh.io>
    description: An HTTP API wrapping the Android Debug Bridge.
    license: Apache 2.0
    formats:
      - deb
      - rpm
    dependencies:
      - android-tools
