openapi: 3.0.2
info:
  title: Android Web Debugging Bridge
  description: This API exposes the functionality of Google's 'Android Debug Bridge'
    utility.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Read more about ADB.
  url: https://developer.android.com/studio/command-line/adb
tags:
- name: general commands
  description: Information and status of ADB.
paths:
  /help/:
    get:
      tags:
      - general commands
      summary: ADB's help page.
      description: Returns the result of `adb help`.
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
                description: Raw contents of ADB's help page.
                example: |
                  Android Debug Bridge version 1.0.41
                  Version 29.0.3
                  Installed as /usr/bin/adb
                  ...
        502:
          description: Error communicating with ADB.
          content:
            text/plain:
              schema:
                type: string
                description: Error message from Go.
